OneTrip3G.Web/Areas/Admin/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using OneTrip3G.IServices;
using OneTrip3G.Models;
using OneTrip3G.Web.Extensions;
using OneTrip3G.Models.Entities;

namespace OneTrip3G.Web.Areas.Admin.Controllers
{
    public class PlacesController : BaseController
    {
        private readonly IPlaceService service;

        public PlacesController(IPlaceService service)
        {
            this.service = service;
        }

        public ActionResult Index(int? page)
        {
            var places = service.GetPlaces().ToPagedList(page.HasValue ? page.Value -1 : 0, MvcApplication.Settings.ListPageSize);
            return View(places);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreatePlace createPlace)
        {
            if (ModelState.IsValid)
            {
                service.CreatePlace(createPlace);
                return RedirectToAction("Index").AndNotice("添加成功！");
            }
            return View(createPlace);
        }

        public ActionResult Edit(int id)
        {
            var place = service.GetPlace(id);
            return View(place);
        }

        [HttpPost]
        public ActionResult Edit(EditPlace model)
        {
            if (ModelState.IsValid)
            {
                service.UpdatePlace(model);
                return RedirectToAction("Index").AndNotice("修改成功！");
            }
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            service.DeletePlace(id);
            return RedirectToAction("Index").AndNotice("删除成功！");
        }

        public JsonResult CheckUrlKeyExist(string urlKey)
        {
            var result = service.CheckPlaceExist(urlKey);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

OneTrip3G.Web/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OneTrip3G.IServices;
using OneTrip3G.Models;

namespace OneTrip3G.Web.Controllers
{
    public class PlacesController : Controller
    {
        private readonly IPlaceService placeService;

        public PlacesController(IPlaceService placeService)
        {
            this.placeService = placeService;
        }

        public ActionResult Show(string urlKey)
        {
            var place = placeService.GetByUrlKey(urlKey);

            var placeViewModel = new ShowPlace
            {
                UrlKey = place.EnglishName,
                Name = place.Name,
                VideoFile = place.VideoFile,
                MapFile = place.MapFile,
                MapThumbnailFile = place.MapThumbnailFile
            };
            return View(placeViewModel);
        }

        public ActionResult Map(string urlKey)
        {
            var place = placeService.GetByUrlKey(urlKey);

            var placeViewModel = new ShowPlace
            {
                UrlKey = place.EnglishName,
                Name = place.Name,
                VideoFile = place.VideoFile,
                MapFile = place.MapFile,
                MapThumbnailFile = place.MapThumbnailFile
            };
            return View(placeViewModel);
        }

    }
}

OneTrip3G.Web/Views/Places/Map.cshtml
@model OneTrip3G.Models.ShowPlace
@{
    ViewBag.Title = Model.Name;
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=4.0, user-scalable=yes">
    <title>@ViewBag.Title - @Html.GlobalSettings().SiteName</title>
    @Html.Raw(Html.RenderCssHere(new List<IClientDependencyPath> 
    {
        new BasicPath("Base", "~/Content"),
        new BasicPath("BaseCss", "~/Content/Css"),
        new BasicPath("Mobile", "~/Content/Mobiles")
    }))
    @{
        Html.RequiresCss("Base.css", "Mobile", 10)
            .RequiresCss("screen.css", "Base", 0);
    }
</head>
<body>
    <div class="frame">
        <img class="bigMap" src="@Url.Content(Model.MapFile)" title="@(Model.Name + "地图")" alt="@(Model.Name + "地图")" />
        <p class="font18">两指捏合缩放图片</p>
        <p><a href="@Url.Action("Show", "Places", new { @urlKey = Model.UrlKey })">返回上一页</a></p>
    </div>
</body>
</html>

OneTrip3G.Web/Views/Places/Show.cshtml
@model OneTrip3G.Models.ShowPlace
@{
    ViewBag.Title = Model.Name;
}
@section scripts {
    <script type="text/javascript">
        _V_.options.flash.swf = "@Url.Content("~/Content/video.swf")";
    </script>
}
<div class="big-logo small">
    <img alt="壹旅游" title="壹旅游" src="@Url.Content("~/Content/Images/Mobiles/logo.png")" /> 
</div>
<h2>@Model.Name</h2>
<div class="map">
    <h3>地图</h3>
    <a href="@Url.Action("Map", "Places", new { @urlKey = Model.UrlKey })" title="@(Model.Name + "地图")">
        <img class="smallMap" src="@Url.Content(Model.MapThumbnailFile)" title="@(Model.Name + "地图")" alt="@(Model.Name + "地图")" />
    </a>
    <h5>点击小图查看大图</h5>
</div>
<div class="video">
    <h3>视频</h3>
    <video id="placeVideo" class="video-js vjs-default-skin" controls preload="none" width="250"
      poster="" data-setup="{}">
        <source src="@Url.Content(Model.VideoFile)" type='video/mp4' />
    </video>
</div>